name: Create node.js demo app image and push

on:
  push:
    branches:
      - main

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './node'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --target production --tag ghcr.io/<your-GitHub-username>/node-demoapp:latest
              docker push ghcr.io/<your-GitHub-username>/node-demoapp:latest
