name: Create java demo app image and push

on:
  push:
    branches: ['main']
    paths: ['java/**']

jobs:
  push_to_registry:
    name: Push docker image to ghcr
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    defaults:
      run:
        working-directory: './java'
        
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
     
      - name: 'Build and Push Multi-Arch Image'
        run: |
          docker buildx create --use
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --target production \
            --tag ghcr.io/pjuentgen/java-demoapp:latest \
            --push
